version: '3'
services:

  book-catalog:
    image: book-catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - DATABASE_URL=postgresql://shivpart4_user:XnIyTuGrFo4km1wu3zHWPGvIDdP5Y90n@dpg-crntc0u8ii6s73evoos0-a.oregon-postgres.render.com/shivpart4
    restart: "no"

  inventory-management:
    image: inventory-management
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
     - "8082:8082"
    environment:
      - PORT=8082
      - DATABASE_URL=postgresql://shivpart4_user:XnIyTuGrFo4km1wu3zHWPGvIDdP5Y90n@dpg-crntc0u8ii6s73evoos0-a.oregon-postgres.render.com/shivpart4
    restart: "no"